name: CI for CRUD App
run-name: CI triggered by ${{ github.actor }} For ${{ github.event_name }} event

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017
        options: --health-cmd="mongod --version" --health-interval=10s --health-timeout=5s --health-retries=5

    strategy:
      matrix:
        node-version: [23.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
        
    - name: Install yarn Globally
      run: npm install -g yarn
      
    - name: Install dependencies
      run: yarn install
      
    - name: Build the app
      run: yarn build

    - name: Run tests
      run: yarn test
