name: CI for CRUD App
run-name: CI triggered by ${{ github.actor }} For ${{ github.event_name }} event

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x, 23.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
        
    - name: Install yarn Globally
      run: npm install -g yarn
      
    - name: Install dependencies
      run: yarn install
      
    - run: yarn build --if-present
    - run: yarn test
